name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  push-image:
    name: Push Image
    permissions: write-all
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './app'
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'Build Inventory Image'
        run: |
          docker build . --tag ghcr.io/ai-whiteboard/poc-graphql:latest
          docker push ghcr.io/ai-whiteboard/poc-graphql:latest